export const ENDPOINTS = {
  auth: {
    signup: '/auth/signup',
    login: '/auth/login',
    logout: '/auth/logout',
    google: '/auth/google',
    verify: '/auth/verify',
    refresh: '/auth/refresh',
  },
  profile: {
    me: '/profile/me',
    update: '/profile/me',
    preferences: '/profile/preferences',
    linkAccount: '/profile/link-account',
    linkedAccounts: '/profile/linked-accounts',
  },
  dashboard: {
    summary: '/dashboard/summary',
    wealthGrowth: '/dashboard/wealth-growth',
    smartSavings: '/dashboard/smart-savings',
    fraudProtection: '/dashboard/fraud-protection',
    sme: '/dashboard/sme',
    smeAnalytics: '/dashboard/sme-analytics',
    freelancer: '/dashboard/freelancer',
    entrepreneur: '/dashboard/entrepreneur',
    profile: '/dashboard/profile-data',
  },
  transactions: {
    list: '/transactions',
    create: '/transactions',
    detail: (id: string) => `/transactions/${id}`,
    update: (id: string) => `/transactions/${id}`,
    delete: (id: string) => `/transactions/${id}`,
  },
  savings: {
    goals: '/savings/goals',
    goalDetail: (id: string) => `/savings/goals/${id}`,
    roundUps: '/savings/round-ups',
  },
  fraud: {
    check: '/fraud/check',
    events: '/fraud/events',
    resolveEvent: (id: string) => `/fraud/events/${id}/resolve`,
  },
  ai: {
    insights: '/ai/insights',
    askCoach: '/ai/coach/ask',
    morningBriefing: '/ai/coach/morning-briefing',
    suggestions: '/ai/suggestions',
    updateSuggestion: (id: string) => `/ai/suggestions/${id}`,
  },
  business: {
    health: '/business/health',
    forecast: '/business/forecast',
    vendors: '/business/vendors',
    aiAdvice: '/business/ai-advice',
  },
  onboarding: {
    financialInterview: '/onboarding/financial-interview',
    financialProfile: '/onboarding/financial-profile',
  },
};
