/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: '#f7fafd',
        'surface-dim': '#d7dadd',
        'surface-bright': '#f7fafd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f7',
        'surface-container': '#ebeef1',
        'surface-container-high': '#e5e8eb',
        'surface-container-highest': '#e0e3e6',
        'on-surface': '#181c1e',
        'on-surface-variant': '#43474d',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eef1f4',
        outline: '#74777e',
        'outline-variant': '#c4c6ce',
        'surface-tint': '#49607e',
        primary: '#000f22',
        'on-primary': '#ffffff',
        'primary-container': '#0a2540',
        'on-primary-container': '#768dad',
        'inverse-primary': '#b0c8eb',
        secondary: '#006b5a',
        'on-secondary': '#ffffff',
        'secondary-container': '#54f8d7',
        'on-secondary-container': '#00705e',
        'secondary-fixed': '#58fbda',
        'secondary-fixed-dim': '#2cdebf',
        tertiary: '#060045',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#150082',
        'on-tertiary-container': '#7f7bff',
        'tertiary-fixed': '#e2dfff',
        'tertiary-fixed-dim': '#c3c0ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d2e4ff',
        'primary-fixed-dim': '#b0c8eb',
        'on-primary-fixed': '#001c37',
        'on-primary-fixed-variant': '#314865',
        'on-secondary-fixed': '#00201a',
        'on-secondary-fixed-variant': '#005143',
        'on-tertiary-fixed': '#0f0069',
        'on-tertiary-fixed-variant': '#321ed2',
        background: '#f7fafd',
        'on-background': '#181c1e',
        'surface-variant': '#e0e3e6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '48px',
        md: '24px',
        sm: '12px',
        xs: '4px',
        lg: '48px',
        xl: '80px',
        base: '8px',
      },
      fontFamily: {
        'display-lg': ['Geist'],
        'headline-lg': ['Geist'],
        'headline-lg-mobile': ['Geist'],
        'headline-md': ['Geist'],
        'label-md': ['Geist'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        caption: ['Inter'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
