/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        // Core brand palette
        'brand-primary': '#0A1F5C',
        'brand-secondary': '#08142E',
        'brand-text': '#1A1A1A',
        'brand-text-secondary': '#43474D',
        'brand-charcoal': '#1A1A1A',
        'brand-success': '#2E7D5B',
        'brand-warning': '#C99A2E',
        'brand-error': '#8C3A3A',

        // Surface colors
        'chip-bg': 'rgba(8,20,46,0.04)',
        'surface-border': '#E4E7EE',
        'error-bg': '#F6E7E7',

        'surface-bright': '#FFFFFF',
        'surface-dim': 'rgba(8,20,46,0.06)',
        'surface': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#FFFFFF',
        'surface-container': '#FFFFFF',
        'surface-container-high': '#FFFFFF',
        'surface-container-highest': '#FFFFFF',
        'on-surface': '#08142E',
        'on-surface-variant': '#43474d',
        'inverse-surface': '#08142E',
        'inverse-on-surface': '#FFFFFF',
        'outline': 'rgba(8,20,46,0.25)',
        'outline-variant': '#E4E7EE',
        'surface-tint': '#0A1F5C',
        'surface-variant': '#FFFFFF',

        primary: '#0A1F5C',
        'on-primary': '#FFFFFF',
        'primary-container': '#08142E',
        'on-primary-container': '#FFFFFF',

        secondary: '#08142E',
        'on-secondary': '#FFFFFF',
        'secondary-container': 'rgba(8, 20, 46, 0.08)',
        'on-secondary-container': '#08142E',
        'secondary-fixed': 'rgba(8, 20, 46, 0.08)',
        'secondary-fixed-dim': 'rgba(8, 20, 46, 0.12)',

        tertiary: '#060045',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#150082',
        'on-tertiary-container': '#7f7bff',
        'tertiary-fixed': '#e2dfff',
        'tertiary-fixed-dim': '#c3c0ff',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'primary-fixed': '#E8EDF5',
        'primary-fixed-dim': '#B8C4E0',
        'on-primary-fixed': '#0A1F5C',
        'on-primary-fixed-variant': '#0A1F5C',
        'on-secondary-fixed': '#08142E',
        'on-secondary-fixed-variant': '#08142E',
        'on-tertiary-fixed': '#0f0069',
        'on-tertiary-fixed-variant': '#321ed2',

        background: '#FFFFFF',
        'on-background': '#1A1A1A',
      },
      borderRadius: {
        card: '18px',
        button: '9999px',
        input: '14px',
        'icon-container': '9999px',
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        pill: '9999px',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '24px',
        gutter: '24px',
        'margin-desktop': '48px',
        md: '24px',
        sm: '12px',
        xs: '4px',
        lg: '48px',
        xl: '80px',
        base: '8px',
      },
      fontFamily: {
        logo: ['Cinzel_700Bold'],
        'logo-semibold': ['Cinzel_600SemiBold'],
        display: ['Montserrat_800ExtraBold'],
        'display-bold': ['Montserrat_700Bold'],
        body: ['Montserrat_400Regular'],
        'body-medium': ['Montserrat_500Medium'],
        'body-semibold': ['Montserrat_600SemiBold'],
        'body-bold': ['Montserrat_700Bold'],
        caption: ['Montserrat_500Medium'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        caption: ['14px', { lineHeight: '20px', fontWeight: '500' }],
        button: ['16px', { lineHeight: '22px', fontWeight: '600' }],
        numeral: ['36px', { lineHeight: '40px', fontWeight: '800' }],
        'onboarding-statement': ['38px', { lineHeight: '42px', fontWeight: '800' }],
      },
      boxShadow: {
        card: '0 2px 12px rgba(8, 20, 46, 0.06)',
        button: '0 4px 20px rgba(8, 20, 46, 0.15)',
        'tab-bar': '0 -1px 0 rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
};
