/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        surface: '#F7F9FC',
        'surface-dim': '#d7dadd',
        'surface-bright': '#F7F9FC',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f7',
        'surface-container': '#ebeef1',
        'surface-container-high': '#e5e8eb',
        'surface-container-highest': '#e0e3e6',
        'on-surface': '#1A1A1A',
        'on-surface-variant': '#43474d',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eef1f4',
        outline: '#74777e',
        'outline-variant': '#c4c6ce',
        'surface-tint': '#0A1F5C',
        primary: '#0A1F5C',
        'on-primary': '#FFFFFF',
        'primary-container': '#08142E',
        'on-primary-container': '#B8C4E0',
        'inverse-primary': '#D4AF37',
        secondary: '#D4AF37',
        'on-secondary': '#1A1A1A',
        'secondary-container': '#F4D35E',
        'on-secondary-container': '#1A1A1A',
        'secondary-fixed': '#F4D35E',
        'secondary-fixed-dim': '#D4AF37',
        tertiary: '#060045',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#150082',
        'on-tertiary-container': '#7f7bff',
        'tertiary-fixed': '#e2dfff',
        'tertiary-fixed-dim': '#c3c0ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#E8EDF5',
        'primary-fixed-dim': '#B8C4E0',
        'on-primary-fixed': '#0A1F5C',
        'on-primary-fixed-variant': '#0A1F5C',
        'on-secondary-fixed': '#1A1A1A',
        'on-secondary-fixed-variant': '#1A1A1A',
        'on-tertiary-fixed': '#0f0069',
        'on-tertiary-fixed-variant': '#321ed2',
        background: '#F7F9FC',
        'on-background': '#1A1A1A',
        'surface-variant': '#e0e3e6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '48px',
        md: '24px',
        sm: '12px',
        xs: '4px',
        lg: '48px',
        xl: '80px',
        base: '8px',
      },
      fontFamily: {
        'display-lg': ['Geist-SemiBold'],
        'headline-lg': ['Geist-SemiBold'],
        'headline-lg-mobile': ['Geist-SemiBold'],
        'headline-md': ['Geist-Medium'],
        'label-md': ['Geist-Medium'],
        'body-lg': ['Inter_400Regular'],
        'body-md': ['Inter_400Regular'],
        caption: ['Inter_500Medium'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
